### PR TITLE
Fixed a couple of typos

### PR DESCRIPTION
**Pull request by mcls**

### CODE REVIEW

**Comment by solnic** [comment]
Thank you. I will never learn how to spell those words ;)

**Comment by mcls** [comment]
Then that "Edit  on GitHub" link is golden :D
Op 8 jan. 2015 22:39 schreef "Piotr Solnica" <notifications@github.com>:

**Comment by solnic** [comment]
Yes I must say it's been a huge success so far haha :)

**Comment by adz** [comment]
It takes unnecessary persistence to be compliant with English.

**Comment by solnic** [comment]
I see what you did there

**Pull request merged**
