### PR TITLE
[WIP] Combining relationships docs

### PR DESCRIPTION
**Pull request by abrthel**
Seeing as how I've seen the question asked a number of times before in gitter, today I spent more time than I care to admit and wrote a docs page explaining how to combine relations a number of ways that are commonly asked about.

It's literally a first draft so expect a number of spelling errors and issues of that kind. I'm also not married to it, so feel free to trash, hack and/or slash whatever is needed to make it fit with the overall plan. I would have discussed it on gitter before starting but we're in much different TimeZones and got impatient 😈

Instead of adding the contents of the page to the Associations page, I decided to create a new page for the simple reason, I figured the page would be longer and it didn't feel right introducing such an important concept under all of the associations stuff.

**Important**
I'm still learning my way through ROM and I made a few assumptions about combines and their overall purpose. If I'm wrong, leave a comment correcting the record and I'll fix it up.

### CODE REVIEW

**Comment by abrthel** [comment]
@solnic any thoughts on this as it stands? I'm going to finish up my editing tomorrow and it would be helpful to know if I'm on the right track or if this kind of documentation is even needed.

**Comment by solnic** [comment]
@abrthel so sorry for missing this one. I had unwatched this project and missed some stuff :/ I'll check it out and get back to you.

**Comment by abrthel** [comment]
No worries 🙂 

I know I've made a few errors, and I plan on correcting them before its done. Namely conflating combine with sql joins.

**Comment by solnic** [comment]
Shall we wrap this up? :)

**Comment by abrthel** [comment]
For sure!

I plan on writing docs throughout this weekend so it should be ready later today or early tomorrow morning. (plus other changes)

**Comment by abrthel** [comment]
Closed in favor of #213

**Pull request closed without merging**
