### PR TITLE
[learn] introduction/active-record Clarify missing attribute error

### PR DESCRIPTION
**Pull request by abrthel**
Fixes issue #241

I remembered after I was trying to make a more philosophical comparison with this example. 
@janko-m does this make a bit more sense?

### CODE REVIEW

**Comment by janko-m** [comment]
But ROM will also raise a "missing attribute" error:

```rb
user = users_relation
   .select(:name)
   .where(name: name)
   .one

user.email
# ~> ROM::Struct::MissingAttribute
# ~> undefined method `gender' for #<ROM::Struct::User name="Janko"> (attribute not loaded?)
```

So there doesn't seem to be any difference between ROM and ActiveRecord in this particular case.

**Comment by solnic** [comment]
There is a huge difference between how ROM handles attributes vs AR, because struct's are always a true reflection of what the database query returned, whereas with AR, it's just a model instance in a weird state, where data is chucked into its `attributes` hash. With ROM, you get a struct with explicit schema which reflects the query and info about names and types.

Compare:

``` ruby
User.find_by_sql("select email AS user_email FROM users").first
=> #<User id: nil>
```

vs

``` ruby
user = users.with(auto_struct: true).select { email.as(:user_email) }.first
# => #<ROM::Struct::User user_email="admin@rrr.dev">

user.class.schema[:user_email]
# => #<Dry::Types::Definition primitive=String options={} meta={:alias=>:user_email, :source=>:users, :index=>true}>

# also notice that:

user_1 = users.first
# => #<ROM::Struct::User id=1 email="admin@rrr.dev">
user_2 = users.select { email.as(:user_email) }.first
# => #<ROM::Struct::User user_email="admin@rrr.dev">

user_1.class == user_2.class
# => false !!!
```

What this means, is that **ROM keeps track on attributes all the time**. We know their names, aliases, their source relations, whether they are part of a wrapped struct or not etc. It's not a hack where we allow arbitrary data chucked right into some hash, and based on its keys we expose the values, instead we actually handle everything explicitly and the resulting structs are 100% explicit, with attribute schemas.

**Comment by janko-m** [comment]
Wow, that's really interesting. I thought that it's just that, a struct which accepts a Hash of data.

Ok, so, is there some example we can use instead of the current one to illustrate this difference?

**Comment by abrthel** [comment]
I think it's best for now to drop the blurb and error and just compare the syntax and usage until a time where we have a better example.

**Comment by janko-m** [comment]
Yeah, that makes sense to me. I would like the guide to evolve with more examples over time.

**Comment by janko-m** [comment]
Btw, the `user_entity =` in the AR example is not needed anymore, and it also wouldn’t be the AR terminology.

**Comment by abrthel** [comment]
Fixed. Good catch.

**Pull request merged**
