### PR TITLE
Add tag support

### PR DESCRIPTION
**Pull request by elskwid**
I thought I'd give tag support a shot. Here we have basic support for tagging articles and the creation of the tag pages using the included template when the site is built. 

Tag pages look like this:

rom blog 2014-12-31 18-09-38
rom blog 2014-12-31 18-09-50

The tags are displayed in the sidebar when you are viewing an article:

rom blog rom 0 5 0 released 2014-12-31 18-10-28

I kinda like that, it keeps the article nice and clean, but give some additional context. This happens via a `content_for(:sidebar_tags)` block. I also added a `content_for(:sidebar)` block for other stuff we may want to shove in there.

And in case you missed it, the sidebar title is changed:

rom blog 2014-12-31 18-12-32

:fireworks: Happy New Year! :fireworks:

### CODE REVIEW

**Comment by solnic** [comment]
@elskwid thanks, I made some changes and I'm merging this in...lemme know what you think!

**Comment by elskwid** [comment]
I like the counts! Much better than what I had. Thanks @solnic.

**Comment by solnic** [comment]
@elskwid awesome, I felt bad for stepping on your toes like that and I just assumed you'd like those changes. I would've asked but you know, stupid timezones and stuff ;)

**Comment by elskwid** [comment]
@solnic We're collaborating. Don't worry about it at all. If you have a better idea or one you feel strongly about it will all be better in the end. Strong opinions weakly held and that sort of thing.

I am just happy progress is being made.

HAPPY NEW YEAR

**Comment by solnic** [comment]
FULL ACK

**Pull request merged**
