### PR TITLE
Rework the Rails tutorial to reflect 0.6 API changes and new features

### PR DESCRIPTION
**Pull request by maetl**
Topic by topic (more or less page by page, but not exactly):

- [x] Update the Getting Started page to focus more on the ROM API
- [x] Merge Task Index, Task Relations, and Task Mapper into a single page focusing on read queries and - mapping (using subclasses of relation and mappers rather than the DSL)
- [x] Expand Managing Tasks into a more detailed walkthrough focused on building forms, making commands implicit rather than explicit
- [x] Testing in Rails with ROM (how to drop-in ROM without breaking out of Rails conventions)
- [x] Migrations in Rails with ROM (mention ActiveRecord as the default, Sequel as an option, and a forthcoming ROM-provided tool)
- [x] The end, summary, next steps, and other resources

If these pages get unreasonably complicated, I’ll split relations and mappers, and commands and forms into separate pages, though I feel that as a tutorial, they should be together—and that the Rails tutorial should be supplemented by content elsewhere, for example, detailed standalone guides on each of these topics. Something to think about for 1.0 rather than 0.6 perhaps :)

### CODE REVIEW

**Comment by maetl** [comment]
*Note: I’ve swapped around the original description of the PR to this comment, and rewritten the issue with a list of tasks, because it’s going to be easier for me to update all the tutorial pages together in one go.*

First cut of a new Rails tutorial, placing more focus on the intent of the API and becoming familiar with the ROM env.

I also emphasised the fact that ROM readers and relations always return enumerables, as this helps people reason about the code in a less “frameworky” pure Ruby way, which IMO is one of the selling points of ROM.

The first part is messier than I would like because the following command exploded with an infinite HTTP redirect loop when I ran it locally:

```
rails new rom-todo-app -JTS -m http://rom-rb.org/tutorials/code/rom-todo-app-template.rb
```

Everything else worked perfectly fine though.

**Comment by solnic** [comment]
quick note: with rom-rb/rom#155 merged we should use the explicit mapping via `rom.relation(:users).as(:presenters)` instead of reader api (which will probably be (re)moved)

**Comment by maetl** [comment]
Sure... I’ve already made that change in everything I’ve written. Will need to make sure that it doesn’t pop up in other places as well.

**Comment by solnic** [comment]
Just a heads-up that this is now the only remaining task prior 0.6.0.rc release :) NO PRESSURE WHATSOEVER ;) Seriously though, let me know if I can help in any way

**Comment by maetl** [comment]
I’ll push up the final set of updates soon. Would be great to make sure that everything in the tutorial is tested and confirmed correct/working.

**Comment by solnic** [comment]
@maetl fantastic, thank you. I'll go through it and test everything.

**Comment by solnic** [comment]
@maetl could you push what you have and I could finish it if you don't have time? I'd love to push RC this week along with updated website

**Comment by maetl** [comment]
@solnic Almost done. I’ll push the final bits in an hour or two, and you can review/make changes as it makes sense. I’m also happy to revisit and add improvements to this (and encourage others to do the same) after RC and updates are pushed.

**Comment by maetl** [comment]
Pushed the latest now.

**Comment by maetl** [comment]
There’s a couple of references to the Sinatra tutorial that will need to be removed if we want to publish this sooner rather than later.

**Pull request merged**
