### PR TITLE
Update setup-dsl.html.md

### PR DESCRIPTION
**Pull request by mikekreuzer**
Adds an example with a note about needing to use the full path to a file with SQLite - that held me up longer than it should

### CODE REVIEW

**Comment by solnic** [comment]
I believe the path is relative to `Dir.pwd`. Could you verify this before we make this change in the docs? If I'm right, it would be good to explain this properly :)

**Comment by mikekreuzer** [comment]
No you're right, sorry - I must have typed it wrongly somehow before, just tried again & (eg) ''sqlite://test.db'' worked just fine. Damn, sorry!

**Comment by abrthel** [comment]
For future reference, this docs page should be helpful.

http://rom-rb.org/4.0/learn/sql/#sqlite

**Comment by solnic** [comment]
OK cool & no worries :) So I guess we can close this.

**Pull request closed without merging**
